return {
  features = {},
  meta = {
    areas = {},
    info = {
      author = "UnnamedPlayer",
      description = "",
      name = "UnnamedPlayer's Scenario",
      version = "1",
    },
    teams = {
      [1] = {
        id = 1,
        team = {
          ai = true,
          allyTeam = 1,
          gaia = false,
          id = 1,
          name = "1: NullAI",
          side = "",
          allies = {
            [1] = 1,
          },
          color = {
            a = 1,
            b = 0,
            g = 0,
            r = 0.7843137383461,
          },
        },
      },
      [2] = {
        id = 2,
        team = {
          ai = true,
          allyTeam = 2,
          gaia = true,
          id = 2,
          name = "2",
          side = "",
          allies = {
            [1] = 2,
          },
          color = {
            a = 1,
            b = 1,
            g = 1,
            r = 1,
          },
        },
      },
      [3] = {
        id = 0,
        team = {
          allyTeam = 0,
          gaia = false,
          id = 0,
          name = "0",
          side = "",
          allies = {
            [1] = 0,
          },
          color = {
            a = 1,
            b = 1,
            g = 0.35294118523598,
            r = 0.35294118523598,
          },
        },
      },
    },
    triggers = {},
    variables = {},
  },
  units = {
    [1] = {
      angle = 0,
      blocking = false,
      experience = 0,
      fuel = 0,
      id = 10,
      neutral = true,
      teamId = 1,
      tooltip = "Fire - fire",
      unitDefName = "fire",
      x = 334.58563232422,
      y = 144.259765625,
      z = 2325.2883300781,
      commands = {},
      losState = {
        los = true,
        radar = true,
        typed = true,
      },
      states = {
        active = false,
        cloak = false,
        firestate = 2,
        movestate = 0,
        ["repeat"] = false,
        trajectory = false,
      },
    },
    [2] = {
      angle = 39.367713928223,
      blocking = false,
      experience = 0,
      fuel = 0,
      id = 12,
      neutral = false,
      teamId = 1,
      tooltip = "Projector - projector",
      unitDefName = "projector",
      x = 414.1701965332,
      y = 144.259765625,
      z = 2481.1245117188,
      commands = {},
      losState = {
        los = true,
        radar = true,
        typed = true,
      },
      states = {
        active = false,
        cloak = false,
        firestate = 2,
        movestate = 1,
        ["repeat"] = false,
        trajectory = false,
      },
    },
    [3] = {
      angle = -58.968955993652,
      blocking = true,
      experience = 0,
      fuel = 0,
      id = 52,
      neutral = false,
      teamId = 1,
      tooltip = "Crate - crate",
      unitDefName = "crate",
      x = 609.208984375,
      y = 144.259765625,
      z = 3162.0209960938,
      commands = {},
      losState = {
        los = true,
        radar = true,
        typed = true,
      },
      states = {
        active = false,
        cloak = false,
        firestate = 2,
        movestate = 1,
        ["repeat"] = false,
        trajectory = false,
      },
    },
    [4] = {
      angle = 0,
      blocking = false,
      experience = 0,
      fuel = 0,
      id = 5,
      neutral = true,
      teamId = 1,
      tooltip = "Fire - fire",
      unitDefName = "fire",
      x = 224.09625244141,
      y = 144.25999450684,
      z = 2483.626953125,
      commands = {},
      losState = {
        los = true,
        radar = true,
        typed = true,
      },
      states = {
        active = false,
        cloak = false,
        firestate = 2,
        movestate = 0,
        ["repeat"] = false,
        trajectory = false,
      },
    },
    [5] = {
      angle = -58.968955993652,
      blocking = true,
      experience = 0,
      fuel = 0,
      id = 70,
      neutral = false,
      teamId = 1,
      tooltip = "Crate - crate",
      unitDefName = "crate",
      x = 450.62704467773,
      y = 144.2626953125,
      z = 3013.3823242188,
      commands = {},
      losState = {
        los = true,
        radar = true,
        typed = true,
      },
      states = {
        active = false,
        cloak = false,
        firestate = 2,
        movestate = 1,
        ["repeat"] = false,
        trajectory = false,
      },
    },
    [6] = {
      angle = 0,
      blocking = true,
      id = 29,
      neutral = false,
      teamId = 0,
      tooltip = "Gravit - gravit",
      unitDefName = "gravit",
      x = 466.77127075195,
      y = 144.259765625,
      z = 3260.3447265625,
      losState = {
        los = true,
        radar = true,
        typed = true,
      },
    },
    [7] = {
      angle = 0,
      blocking = false,
      experience = 0,
      fuel = 0,
      id = 9,
      neutral = true,
      teamId = 1,
      tooltip = "Fire - fire",
      unitDefName = "fire",
      x = 305.16488647461,
      y = 144.259765625,
      z = 2371.599609375,
      commands = {},
      losState = {
        los = true,
        radar = true,
        typed = true,
      },
      states = {
        active = false,
        cloak = false,
        firestate = 2,
        movestate = 0,
        ["repeat"] = false,
        trajectory = false,
      },
    },
    [8] = {
      angle = -58.968955993652,
      blocking = true,
      experience = 0,
      fuel = 0,
      id = 72,
      neutral = false,
      teamId = 1,
      tooltip = "Crate - crate",
      unitDefName = "crate",
      x = 461.58828735352,
      y = 144.2626953125,
      z = 3073.5451660156,
      commands = {},
      losState = {
        los = true,
        radar = true,
        typed = true,
      },
      states = {
        active = false,
        cloak = false,
        firestate = 2,
        movestate = 1,
        ["repeat"] = false,
        trajectory = false,
      },
    },
    [9] = {
      angle = -58.968955993652,
      blocking = true,
      experience = 0,
      fuel = 0,
      id = 54,
      neutral = false,
      teamId = 1,
      tooltip = "Crate - crate",
      unitDefName = "crate",
      x = 524.32147216797,
      y = 144.259765625,
      z = 3093.5510253906,
      commands = {},
      losState = {
        los = true,
        radar = true,
        typed = true,
      },
      states = {
        active = false,
        cloak = false,
        firestate = 2,
        movestate = 1,
        ["repeat"] = false,
        trajectory = false,
      },
    },
    [10] = {
      angle = -58.968955993652,
      blocking = true,
      experience = 0,
      fuel = 0,
      id = 44,
      neutral = false,
      teamId = 1,
      tooltip = "Crate - crate",
      unitDefName = "crate",
      x = 559.78381347656,
      y = 144.259765625,
      z = 3041.0952148438,
      commands = {},
      losState = {
        los = true,
        radar = true,
        typed = true,
      },
      states = {
        active = false,
        cloak = false,
        firestate = 2,
        movestate = 1,
        ["repeat"] = false,
        trajectory = false,
      },
    },
    [11] = {
      angle = -58.968955993652,
      blocking = true,
      experience = 0,
      fuel = 0,
      id = 64,
      neutral = false,
      teamId = 1,
      tooltip = "Crate - crate",
      unitDefName = "crate",
      x = 512.65216064453,
      y = 144.26348876953,
      z = 3515.9604492188,
      commands = {},
      losState = {
        los = true,
        radar = true,
        typed = true,
      },
      states = {
        active = false,
        cloak = false,
        firestate = 2,
        movestate = 1,
        ["repeat"] = false,
        trajectory = false,
      },
    },
    [12] = {
      angle = -58.968955993652,
      blocking = true,
      experience = 0,
      fuel = 0,
      id = 56,
      neutral = false,
      teamId = 1,
      tooltip = "Crate - crate",
      unitDefName = "crate",
      x = 666.45257568359,
      y = 144.259765625,
      z = 3213.787109375,
      commands = {},
      losState = {
        los = true,
        radar = true,
        typed = true,
      },
      states = {
        active = false,
        cloak = false,
        firestate = 2,
        movestate = 1,
        ["repeat"] = false,
        trajectory = false,
      },
    },
    [13] = {
      angle = 0,
      blocking = false,
      experience = 0,
      fuel = 0,
      id = 7,
      neutral = true,
      teamId = 1,
      tooltip = "Fire - fire",
      unitDefName = "fire",
      x = 467.49322509766,
      y = 144.259765625,
      z = 2215.5476074219,
      commands = {},
      losState = {
        los = true,
        radar = true,
        typed = true,
      },
      states = {
        active = false,
        cloak = false,
        firestate = 2,
        movestate = 0,
        ["repeat"] = false,
        trajectory = false,
      },
    },
    [14] = {
      angle = 0,
      blocking = false,
      experience = 0,
      fuel = 0,
      id = 39,
      neutral = true,
      teamId = 1,
      tooltip = "Fire - fire",
      unitDefName = "fire",
      x = 155.26675415039,
      y = 144.26148986816,
      z = 2494.771484375,
      commands = {},
      losState = {
        los = true,
        radar = true,
        typed = true,
      },
      states = {
        active = false,
        cloak = false,
        firestate = 2,
        movestate = 0,
        ["repeat"] = false,
        trajectory = false,
      },
    },
    [15] = {
      angle = -58.968955993652,
      blocking = true,
      experience = 0,
      fuel = 0,
      id = 40,
      neutral = false,
      teamId = 1,
      tooltip = "Crate - crate",
      unitDefName = "crate",
      x = 495.20208740234,
      y = 144.26268005371,
      z = 2919.6784667969,
      commands = {},
      losState = {
        los = true,
        radar = true,
        typed = true,
      },
      states = {
        active = false,
        cloak = false,
        firestate = 2,
        movestate = 1,
        ["repeat"] = false,
        trajectory = false,
      },
    },
    [16] = {
      angle = -58.968955993652,
      blocking = true,
      experience = 0,
      fuel = 0,
      id = 66,
      neutral = false,
      teamId = 1,
      tooltip = "Crate - crate",
      unitDefName = "crate",
      x = 565.65063476562,
      y = 144.26356506348,
      z = 3473.8791503906,
      commands = {},
      losState = {
        los = true,
        radar = true,
        typed = true,
      },
      states = {
        active = false,
        cloak = false,
        firestate = 2,
        movestate = 1,
        ["repeat"] = false,
        trajectory = false,
      },
    },
    [17] = {
      angle = -58.968955993652,
      blocking = true,
      experience = 0,
      fuel = 0,
      id = 62,
      neutral = false,
      teamId = 1,
      tooltip = "Crate - crate",
      unitDefName = "crate",
      x = 718.27532958984,
      y = 144.259765625,
      z = 3243.7548828125,
      commands = {},
      losState = {
        los = true,
        radar = true,
        typed = true,
      },
      states = {
        active = false,
        cloak = false,
        firestate = 2,
        movestate = 1,
        ["repeat"] = false,
        trajectory = false,
      },
    },
    [18] = {
      angle = -58.968955993652,
      blocking = true,
      experience = 0,
      fuel = 0,
      id = 42,
      neutral = false,
      teamId = 1,
      tooltip = "Crate - crate",
      unitDefName = "crate",
      x = 546.16094970703,
      y = 144.2626953125,
      z = 2970.3491210938,
      commands = {},
      losState = {
        los = true,
        radar = true,
        typed = true,
      },
      states = {
        active = false,
        cloak = false,
        firestate = 2,
        movestate = 1,
        ["repeat"] = false,
        trajectory = false,
      },
    },
    [19] = {
      angle = 0,
      blocking = false,
      experience = 0,
      fuel = 0,
      health = 99.999000549316,
      id = 8,
      neutral = true,
      teamId = 1,
      tooltip = "Fire - fire",
      unitDefName = "fire",
      x = 407.5133972168,
      y = 144.259765625,
      z = 2264.6335449219,
      commands = {},
      losState = {
        los = true,
        radar = true,
        typed = true,
      },
      states = {
        active = false,
        cloak = false,
        firestate = 2,
        movestate = 0,
        ["repeat"] = false,
        trajectory = false,
      },
    },
    [20] = {
      angle = 44.33931350708,
      blocking = false,
      experience = 0,
      fuel = 0,
      id = 11,
      neutral = false,
      teamId = 1,
      tooltip = "Projector - projector",
      unitDefName = "projector",
      x = 370.04434204102,
      y = 144.259765625,
      z = 2572.34765625,
      commands = {},
      losState = {
        los = true,
        radar = true,
        typed = true,
      },
      states = {
        active = false,
        cloak = false,
        firestate = 2,
        movestate = 1,
        ["repeat"] = false,
        trajectory = false,
      },
    },
    [21] = {
      angle = 39.672225952148,
      blocking = false,
      experience = 0,
      fuel = 0,
      id = 15,
      neutral = false,
      teamId = 1,
      tooltip = "Projector - projector",
      unitDefName = "projector",
      x = 586.86541748047,
      y = 144.259765625,
      z = 2334.650390625,
      commands = {},
      losState = {
        los = true,
        radar = true,
        typed = true,
      },
      states = {
        active = false,
        cloak = false,
        firestate = 2,
        movestate = 1,
        ["repeat"] = false,
        trajectory = false,
      },
    },
    [22] = {
      angle = 159.33010864258,
      blocking = true,
      experience = 0,
      fuel = 0,
      id = 48,
      neutral = false,
      teamId = 1,
      tooltip = "Crate - crate",
      unitDefName = "crate",
      x = 669.31378173828,
      y = 144.259765625,
      z = 3087.7551269531,
      commands = {},
      losState = {
        los = true,
        radar = true,
        typed = true,
      },
      states = {
        active = false,
        cloak = false,
        firestate = 2,
        movestate = 1,
        ["repeat"] = false,
        trajectory = false,
      },
    },
    [23] = {
      angle = -58.968955993652,
      blocking = true,
      experience = 0,
      fuel = 0,
      id = 60,
      neutral = false,
      teamId = 1,
      tooltip = "Crate - crate",
      unitDefName = "crate",
      x = 776.10400390625,
      y = 144.26403808594,
      z = 3287.7836914062,
      commands = {},
      losState = {
        los = true,
        radar = true,
        typed = true,
      },
      states = {
        active = false,
        cloak = false,
        firestate = 2,
        movestate = 1,
        ["repeat"] = false,
        trajectory = false,
      },
    },
    [24] = {
      angle = 0,
      blocking = false,
      experience = 0,
      fuel = 0,
      id = 6,
      neutral = true,
      teamId = 1,
      tooltip = "Fire - fire",
      unitDefName = "fire",
      x = 230.37547302246,
      y = 144.259765625,
      z = 2426.1921386719,
      commands = {},
      losState = {
        los = true,
        radar = true,
        typed = true,
      },
      states = {
        active = false,
        cloak = false,
        firestate = 2,
        movestate = 0,
        ["repeat"] = false,
        trajectory = false,
      },
    },
    [25] = {
      angle = -58.968955993652,
      blocking = true,
      experience = 0,
      fuel = 0,
      id = 68,
      neutral = false,
      teamId = 1,
      tooltip = "Crate - crate",
      unitDefName = "crate",
      x = 452.33023071289,
      y = 144.26124572754,
      z = 3450.1904296875,
      commands = {},
      losState = {
        los = true,
        radar = true,
        typed = true,
      },
      states = {
        active = false,
        cloak = false,
        firestate = 2,
        movestate = 1,
        ["repeat"] = false,
        trajectory = false,
      },
    },
    [26] = {
      angle = -37.823570251465,
      blocking = true,
      experience = 0,
      fuel = 0,
      id = 46,
      neutral = false,
      teamId = 1,
      tooltip = "Crate - crate",
      unitDefName = "crate",
      x = 603.24438476562,
      y = 144.259765625,
      z = 3090.6596679688,
      commands = {},
      losState = {
        los = true,
        radar = true,
        typed = true,
      },
      states = {
        active = false,
        cloak = false,
        firestate = 2,
        movestate = 1,
        ["repeat"] = false,
        trajectory = false,
      },
    },
    [27] = {
      angle = 20.814603805542,
      blocking = false,
      experience = 0,
      fuel = 0,
      id = 14,
      neutral = false,
      teamId = 1,
      tooltip = "Projector - projector",
      unitDefName = "projector",
      x = 540.27740478516,
      y = 144.259765625,
      z = 2372.9377441406,
      commands = {},
      losState = {
        los = true,
        radar = true,
        typed = true,
      },
      states = {
        active = false,
        cloak = false,
        firestate = 2,
        movestate = 1,
        ["repeat"] = false,
        trajectory = false,
      },
    },
    [28] = {
      angle = -58.968955993652,
      blocking = true,
      experience = 0,
      fuel = 0,
      id = 58,
      neutral = false,
      teamId = 1,
      tooltip = "Crate - crate",
      unitDefName = "crate",
      x = 781.86535644531,
      y = 144.259765625,
      z = 3209.451171875,
      commands = {},
      losState = {
        los = true,
        radar = true,
        typed = true,
      },
      states = {
        active = false,
        cloak = false,
        firestate = 2,
        movestate = 1,
        ["repeat"] = false,
        trajectory = false,
      },
    },
    [29] = {
      angle = -58.968955993652,
      blocking = true,
      experience = 0,
      fuel = 0,
      id = 50,
      neutral = false,
      teamId = 1,
      tooltip = "Crate - crate",
      unitDefName = "crate",
      x = 709.88671875,
      y = 144.259765625,
      z = 3151.0563964844,
      commands = {},
      losState = {
        los = true,
        radar = true,
        typed = true,
      },
      states = {
        active = false,
        cloak = false,
        firestate = 2,
        movestate = 1,
        ["repeat"] = false,
        trajectory = false,
      },
    },
    [30] = {
      angle = 22.281999588013,
      blocking = false,
      experience = 0,
      fuel = 0,
      id = 13,
      neutral = false,
      teamId = 1,
      tooltip = "Projector - projector",
      unitDefName = "projector",
      x = 482.8525390625,
      y = 144.259765625,
      z = 2426.0490722656,
      commands = {},
      losState = {
        los = true,
        radar = true,
        typed = true,
      },
      states = {
        active = false,
        cloak = false,
        firestate = 2,
        movestate = 1,
        ["repeat"] = false,
        trajectory = false,
      },
    },
  },
}
