return {
  features = {},
  meta = {
    areas = {},
    info = {
      author = "UnnamedPlayer",
      description = "",
      name = "UnnamedPlayer's Scenario",
      version = "1",
    },
    teams = {
      [1] = {
        id = 1,
        team = {
          ai = true,
          allyTeam = 1,
          gaia = false,
          id = 1,
          name = "1: NullAI",
          side = "",
          allies = {
            [1] = 1,
          },
          color = {
            a = 1,
            b = 0,
            g = 0,
            r = 0.7843137383461,
          },
        },
      },
      [2] = {
        id = 2,
        team = {
          ai = true,
          allyTeam = 2,
          gaia = true,
          id = 2,
          name = "2",
          side = "",
          allies = {
            [1] = 2,
          },
          color = {
            a = 1,
            b = 1,
            g = 1,
            r = 1,
          },
        },
      },
      [3] = {
        id = 0,
        team = {
          allyTeam = 0,
          gaia = false,
          id = 0,
          name = "0",
          side = "",
          allies = {
            [1] = 0,
          },
          color = {
            a = 1,
            b = 1,
            g = 0.35294118523598,
            r = 0.35294118523598,
          },
        },
      },
    },
    triggers = {},
    variables = {},
  },
  units = {
    [1] = {
      angle = -68.960105895996,
      
      experience = 0,
      fuel = 0,
      id = 177,
      neutral = false,
      teamId = 1,
      tooltip = "Projector - projector",
      unitDefName = "projector",
      x = 790.48352050781,
      y = 144.259765625,
      z = 744.78271484375,
      commands = {},
      losState = {
        los = true,
        radar = true,
        typed = true,
      },
      states = {
        active = false,
        cloak = false,
        firestate = 2,
        movestate = 1,
        ["repeat"] = false,
        trajectory = false,
      },
    },
    [2] = {
      angle = -59.235824584961,
      
      experience = 0,
      fuel = 0,
      id = 179,
      neutral = false,
      teamId = 1,
      tooltip = "Projector - projector",
      unitDefName = "projector",
      x = 819.39477539062,
      y = 144.259765625,
      z = 812.36956787109,
      commands = {},
      losState = {
        los = true,
        radar = true,
        typed = true,
      },
      states = {
        active = false,
        cloak = false,
        firestate = 2,
        movestate = 1,
        ["repeat"] = false,
        trajectory = false,
      },
    },
    [3] = {
      angle = 116.19347381592,
      
      experience = 0,
      fuel = 0,
      id = 126,
      neutral = false,
      teamId = 1,
      tooltip = "Crate - crate",
      unitDefName = "crate",
      x = 567.27294921875,
      y = 144.259765625,
      z = 3444.7158203125,
      commands = {},
      losState = {
        los = true,
        radar = true,
        typed = true,
      },
      states = {
        active = false,
        cloak = false,
        firestate = 2,
        movestate = 1,
        ["repeat"] = false,
        trajectory = false,
      },
    },
    [4] = {
      angle = -72.277923583984,
      
      experience = 0,
      fuel = 0,
      id = 178,
      neutral = false,
      teamId = 1,
      tooltip = "Projector - projector",
      unitDefName = "projector",
      x = 809.0341796875,
      y = 144.259765625,
      z = 776.98937988281,
      commands = {},
      losState = {
        los = true,
        radar = true,
        typed = true,
      },
      states = {
        active = false,
        cloak = false,
        firestate = 2,
        movestate = 1,
        ["repeat"] = false,
        trajectory = false,
      },
    },
    [5] = {
      angle = 0,
      
      experience = 0,
      fuel = 0,
      id = 266,
      neutral = true,
      teamId = 1,
      tooltip = "Fire - fire",
      unitDefName = "fire",
      x = 507.95147705078,
      y = 144.259765625,
      z = 2264.5278320312,
      commands = {},
      losState = {
        los = true,
        radar = true,
        typed = true,
      },
      states = {
        active = false,
        cloak = false,
        firestate = 2,
        movestate = 0,
        ["repeat"] = false,
        trajectory = false,
      },
    },
    [6] = {
      angle = 0,
      
      experience = 0,
      fuel = 0,
      id = 260,
      neutral = true,
      teamId = 1,
      tooltip = "Fire - fire",
      unitDefName = "fire",
      x = 368.94647216797,
      y = 144.259765625,
      z = 2289.1140136719,
      commands = {},
      losState = {
        los = true,
        radar = true,
        typed = true,
      },
      states = {
        active = false,
        cloak = false,
        firestate = 2,
        movestate = 0,
        ["repeat"] = false,
        trajectory = false,
      },
    },
    [7] = {
      angle = -14.174831390381,
      
      experience = 0,
      fuel = 0,
      id = 176,
      neutral = false,
      teamId = 1,
      tooltip = "Projector - projector",
      unitDefName = "projector",
      x = 611.10009765625,
      y = 144.259765625,
      z = 612.72430419922,
      commands = {},
      losState = {
        los = true,
        radar = true,
        typed = true,
      },
      states = {
        active = false,
        cloak = false,
        firestate = 2,
        movestate = 1,
        ["repeat"] = false,
        trajectory = false,
      },
    },
    [8] = {
      angle = 0,
      
      experience = 0,
      fuel = 0,
      id = 172,
      neutral = false,
      teamId = 1,
      tooltip = "Canister - canister",
      unitDefName = "canister",
      x = 207.9641418457,
      y = 144.26293945312,
      z = 948.37982177734,
      commands = {},
      losState = {
        los = true,
        radar = true,
        typed = true,
      },
      states = {
        active = false,
        cloak = false,
        firestate = 2,
        movestate = 1,
        ["repeat"] = false,
        trajectory = false,
      },
    },
    [9] = {
      angle = 0,
      
      experience = 0,
      fuel = 0,
      id = 125,
      neutral = false,
      teamId = 1,
      tooltip = "Crate - crate",
      unitDefName = "crate",
      x = 188.71832275391,
      y = 144.26591491699,
      z = 3244.0234375,
      commands = {},
      losState = {
        los = true,
        radar = true,
        typed = true,
      },
      states = {
        active = false,
        cloak = false,
        firestate = 2,
        movestate = 1,
        ["repeat"] = false,
        trajectory = false,
      },
    },
    [10] = {
      angle = 30.07833480835,
      
      experience = 0,
      fuel = 0,
      id = 238,
      neutral = false,
      teamId = 1,
      tooltip = "Projector - projector",
      unitDefName = "projector",
      x = 370.40441894531,
      y = 144.259765625,
      z = 2457.1708984375,
      commands = {},
      losState = {
        los = true,
        radar = true,
        typed = true,
      },
      states = {
        active = false,
        cloak = false,
        firestate = 2,
        movestate = 1,
        ["repeat"] = false,
        trajectory = false,
      },
    },
    [11] = {
      angle = 0,
      
      experience = 0,
      fuel = 0,
      id = 262,
      neutral = true,
      teamId = 1,
      tooltip = "Fire - fire",
      unitDefName = "fire",
      x = 421.60272216797,
      y = 144.259765625,
      z = 2232.9409179688,
      commands = {},
      losState = {
        los = true,
        radar = true,
        typed = true,
      },
      states = {
        active = false,
        cloak = false,
        firestate = 2,
        movestate = 0,
        ["repeat"] = false,
        trajectory = false,
      },
    },
    [12] = {
      angle = 95.356948852539,
      
      experience = 0,
      fuel = 0,
      id = 149,
      neutral = false,
      teamId = 1,
      tooltip = "Crate - crate",
      unitDefName = "crate",
      x = 910.541015625,
      y = 144.259765625,
      z = 2651.0258789062,
      commands = {},
      losState = {
        los = true,
        radar = true,
        typed = true,
      },
      states = {
        active = false,
        cloak = false,
        firestate = 2,
        movestate = 1,
        ["repeat"] = false,
        trajectory = false,
      },
    },
    [13] = {
      angle = 120.28147125244,
      
      experience = 0,
      fuel = 0,
      id = 147,
      neutral = false,
      teamId = 1,
      tooltip = "Crate - crate",
      unitDefName = "crate",
      x = 849.75054931641,
      y = 144.26005554199,
      z = 2591.1259765625,
      commands = {},
      losState = {
        los = true,
        radar = true,
        typed = true,
      },
      states = {
        active = false,
        cloak = false,
        firestate = 2,
        movestate = 1,
        ["repeat"] = false,
        trajectory = false,
      },
    },
    [14] = {
      angle = 128.5669708252,
      
      experience = 0,
      fuel = 0,
      id = 124,
      neutral = false,
      teamId = 1,
      tooltip = "Crate - crate",
      unitDefName = "crate",
      x = 216.04779052734,
      y = 144.26452636719,
      z = 3172.984375,
      commands = {},
      losState = {
        los = true,
        radar = true,
        typed = true,
      },
      states = {
        active = false,
        cloak = false,
        firestate = 2,
        movestate = 1,
        ["repeat"] = false,
        trajectory = false,
      },
    },
    [15] = {
      angle = 0,
      
      experience = 0,
      fuel = 0,
      id = 170,
      neutral = true,
      teamId = 1,
      tooltip = "Fire - fire",
      unitDefName = "fire",
      x = 717.46337890625,
      y = 144.259765625,
      z = 722.99053955078,
      commands = {},
      losState = {
        los = true,
        radar = true,
        typed = true,
      },
      states = {
        active = false,
        cloak = false,
        firestate = 2,
        movestate = 0,
        ["repeat"] = false,
        trajectory = false,
      },
    },
    [16] = {
      angle = 15.202461242676,
      
      experience = 0,
      fuel = 0,
      id = 173,
      neutral = false,
      teamId = 1,
      tooltip = "Projector - projector",
      unitDefName = "projector",
      x = 463.20910644531,
      y = 144.259765625,
      z = 617.34368896484,
      commands = {},
      losState = {
        los = true,
        radar = true,
        typed = true,
      },
      states = {
        active = false,
        cloak = false,
        firestate = 2,
        movestate = 1,
        ["repeat"] = false,
        trajectory = false,
      },
    },
    [17] = {
      angle = -73.239250183105,
      
      experience = 0,
      fuel = 0,
      id = 180,
      neutral = false,
      teamId = 1,
      tooltip = "Projector - projector",
      unitDefName = "projector",
      x = 823.45391845703,
      y = 144.259765625,
      z = 848.46228027344,
      commands = {},
      losState = {
        los = true,
        radar = true,
        typed = true,
      },
      states = {
        active = false,
        cloak = false,
        firestate = 2,
        movestate = 1,
        ["repeat"] = false,
        trajectory = false,
      },
    },
    [18] = {
      angle = 55.516231536865,
      
      experience = 0,
      fuel = 0,
      id = 232,
      neutral = false,
      teamId = 1,
      tooltip = "Projector - projector",
      unitDefName = "projector",
      x = 401.17984008789,
      y = 144.259765625,
      z = 2413.6528320312,
      commands = {},
      losState = {
        los = true,
        radar = true,
        typed = true,
      },
      states = {
        active = false,
        cloak = false,
        firestate = 2,
        movestate = 1,
        ["repeat"] = false,
        trajectory = false,
      },
    },
    [19] = {
      angle = 0,
      
      experience = 0,
      fuel = 0,
      id = 270,
      neutral = true,
      teamId = 1,
      tooltip = "Fire - fire",
      unitDefName = "fire",
      x = 254.64471435547,
      y = 144.259765625,
      z = 2435.3698730469,
      commands = {},
      losState = {
        los = true,
        radar = true,
        typed = true,
      },
      states = {
        active = false,
        cloak = false,
        firestate = 2,
        movestate = 0,
        ["repeat"] = false,
        trajectory = false,
      },
    },
    [20] = {
      angle = 0,
      
      experience = 0,
      fuel = 0,
      id = 268,
      neutral = true,
      teamId = 1,
      tooltip = "Fire - fire",
      unitDefName = "fire",
      x = 223.72053527832,
      y = 144.26135253906,
      z = 2528.8442382812,
      commands = {},
      losState = {
        los = true,
        radar = true,
        typed = true,
      },
      states = {
        active = false,
        cloak = false,
        firestate = 2,
        movestate = 0,
        ["repeat"] = false,
        trajectory = false,
      },
    },
    [21] = {
      angle = 0,
      
      experience = 0,
      fuel = 0,
      id = 252,
      neutral = true,
      teamId = 1,
      tooltip = "Fire - fire",
      unitDefName = "fire",
      x = 315.89801025391,
      y = 144.259765625,
      z = 2338.4118652344,
      commands = {},
      losState = {
        los = true,
        radar = true,
        typed = true,
      },
      states = {
        active = false,
        cloak = false,
        firestate = 2,
        movestate = 0,
        ["repeat"] = false,
        trajectory = false,
      },
    },
    [22] = {
      angle = 0,
      
      experience = 0,
      fuel = 0,
      id = 166,
      neutral = true,
      teamId = 1,
      tooltip = "Fire - fire",
      unitDefName = "fire",
      x = 681.87133789062,
      y = 144.259765625,
      z = 687.93621826172,
      commands = {},
      losState = {
        los = true,
        radar = true,
        typed = true,
      },
      states = {
        active = false,
        cloak = false,
        firestate = 2,
        movestate = 0,
        ["repeat"] = false,
        trajectory = false,
      },
    },
    [23] = {
      angle = -4.3042707443237,
      
      experience = 0,
      fuel = 0,
      id = 175,
      neutral = false,
      teamId = 1,
      tooltip = "Projector - projector",
      unitDefName = "projector",
      x = 568.79803466797,
      y = 144.259765625,
      z = 604.18023681641,
      commands = {},
      losState = {
        los = true,
        radar = true,
        typed = true,
      },
      states = {
        active = false,
        cloak = false,
        firestate = 2,
        movestate = 1,
        ["repeat"] = false,
        trajectory = false,
      },
    },
    [24] = {
      angle = 65.200065612793,
      
      experience = 0,
      fuel = 0,
      id = 242,
      neutral = false,
      teamId = 1,
      tooltip = "Projector - projector",
      unitDefName = "projector",
      x = 336.28704833984,
      y = 144.259765625,
      z = 2487.3928222656,
      commands = {},
      losState = {
        los = true,
        radar = true,
        typed = true,
      },
      states = {
        active = false,
        cloak = false,
        firestate = 2,
        movestate = 1,
        ["repeat"] = false,
        trajectory = false,
      },
    },
    [25] = {
      angle = 77.162826538086,
      
      experience = 0,
      fuel = 0,
      id = 127,
      neutral = false,
      teamId = 1,
      tooltip = "Crate - crate",
      unitDefName = "crate",
      x = 461.01834106445,
      y = 144.26541137695,
      z = 3482.6809082031,
      commands = {},
      losState = {
        los = true,
        radar = true,
        typed = true,
      },
      states = {
        active = false,
        cloak = false,
        firestate = 2,
        movestate = 1,
        ["repeat"] = false,
        trajectory = false,
      },
    },
    [26] = {
      angle = 0,
      
      experience = 0,
      fuel = 0,
      id = 171,
      neutral = false,
      teamId = 1,
      tooltip = "Canister - canister",
      unitDefName = "canister",
      x = 245.65432739258,
      y = 144.26168823242,
      z = 879.48547363281,
      commands = {},
      losState = {
        los = true,
        radar = true,
        typed = true,
      },
      states = {
        active = false,
        cloak = false,
        firestate = 2,
        movestate = 1,
        ["repeat"] = false,
        trajectory = false,
      },
    },
    [27] = {
      angle = 0,
      
      experience = 0,
      fuel = 0,
      id = 208,
      neutral = false,
      teamId = 0,
      tooltip = "Gravit - gravit",
      unitDefName = "gravit",
      x = 493.70159912109,
      y = 144.259765625,
      z = 1287.3553466797,
      commands = {},
      losState = {
        los = true,
        radar = true,
        typed = true,
      },
      states = {
        active = true,
        cloak = false,
        firestate = 0,
        movestate = 1,
        ["repeat"] = false,
        trajectory = false,
      },
    },
    [28] = {
      angle = 42.754699707031,
      
      experience = 0,
      fuel = 0,
      id = 240,
      neutral = false,
      teamId = 1,
      tooltip = "Projector - projector",
      unitDefName = "projector",
      x = 467.73931884766,
      y = 144.259765625,
      z = 2380.6259765625,
      commands = {},
      losState = {
        los = true,
        radar = true,
        typed = true,
      },
      states = {
        active = false,
        cloak = false,
        firestate = 2,
        movestate = 1,
        ["repeat"] = false,
        trajectory = false,
      },
    },
    [29] = {
      angle = 161.71873474121,
      
      experience = 0,
      fuel = 0,
      id = 29,
      neutral = false,
      teamId = 0,
      tooltip = "Gravit - gravit",
      unitDefName = "gravit",
      x = 507.59808349609,
      y = 144.259765625,
      z = 3170.9125976562,
      commands = {},
      losState = {
        los = true,
        radar = true,
        typed = true,
      },
      states = {
        active = true,
        cloak = false,
        firestate = 0,
        movestate = 1,
        ["repeat"] = false,
        trajectory = false,
      },
    },
    [30] = {
      angle = 5.6570029258728,
      
      experience = 0,
      fuel = 0,
      id = 128,
      neutral = false,
      teamId = 1,
      tooltip = "Crate - crate",
      unitDefName = "crate",
      x = 530.71032714844,
      y = 144.26164245605,
      z = 3515.6955566406,
      commands = {},
      losState = {
        los = true,
        radar = true,
        typed = true,
      },
      states = {
        active = false,
        cloak = false,
        firestate = 2,
        movestate = 1,
        ["repeat"] = false,
        trajectory = false,
      },
    },
    [31] = {
      angle = -1.7666105031967,
      
      experience = 0,
      fuel = 0,
      id = 174,
      neutral = false,
      teamId = 1,
      tooltip = "Projector - projector",
      unitDefName = "projector",
      x = 522.17388916016,
      y = 144.259765625,
      z = 611.62908935547,
      commands = {},
      losState = {
        los = true,
        radar = true,
        typed = true,
      },
      states = {
        active = false,
        cloak = false,
        firestate = 2,
        movestate = 1,
        ["repeat"] = false,
        trajectory = false,
      },
    },
  },
}
